//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SONIP.Common.Resource.Erros {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Base {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Base() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SONIP.Common.Resource.Erros.Base", typeof(Base).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número do cartão não pode ser duplicado.
        /// </summary>
        public static string TagCartaoDuplicado {
            get {
                return ResourceManager.GetString("TagCartaoDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cartão não foi encontrado.
        /// </summary>
        public static string TagCartaoInvalid {
            get {
                return ResourceManager.GetString("TagCartaoInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Cartão não pode ser null.
        /// </summary>
        public static string TagCartaoNull {
            get {
                return ResourceManager.GetString("TagCartaoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Cartão deve conter até 250 digitos.
        /// </summary>
        public static string TagCartaoTamanho {
            get {
                return ResourceManager.GetString("TagCartaoTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O login e a senha não estão correctos..
        /// </summary>
        public static string TagCredencialInvalida {
            get {
                return ResourceManager.GetString("TagCredencialInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A designação não é valida.
        /// </summary>
        public static string TagDesiginacaoInvalid {
            get {
                return ResourceManager.GetString("TagDesiginacaoInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A designação não pode ser nulo.
        /// </summary>
        public static string TagDesignacaoNull {
            get {
                return ResourceManager.GetString("TagDesignacaoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A designação deve conter de 4 a 250 caracteres.
        /// </summary>
        public static string TagDesignacaoTamanho {
            get {
                return ResourceManager.GetString("TagDesignacaoTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email não é valido.
        /// </summary>
        public static string TagEmailInvalido {
            get {
                return ResourceManager.GetString("TagEmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email não pode ser nulo.
        /// </summary>
        public static string TagEmailNull {
            get {
                return ResourceManager.GetString("TagEmailNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email deve conter no maximo 250 caracteres.
        /// </summary>
        public static string TagEmailTamanho {
            get {
                return ResourceManager.GetString("TagEmailTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionario não encontrado.
        /// </summary>
        public static string TagFuncionarioInvalid {
            get {
                return ResourceManager.GetString("TagFuncionarioInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O codigo interno não foi encontrado.
        /// </summary>
        public static string TagIdInvalid {
            get {
                return ResourceManager.GetString("TagIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login duplicado ou já existente.
        /// </summary>
        public static string TagLoginDuplicado {
            get {
                return ResourceManager.GetString("TagLoginDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O login não pode ser nulo.
        /// </summary>
        public static string TagLoginNull {
            get {
                return ResourceManager.GetString("TagLoginNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O login deve conter de 4 à 20 caracteres.
        /// </summary>
        public static string TagLoginTamanho {
            get {
                return ResourceManager.GetString("TagLoginTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O movimento não pode ser duplicado.
        /// </summary>
        public static string TagMovimentoDuplicado {
            get {
                return ResourceManager.GetString("TagMovimentoDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O movimento não foi encontrado.
        /// </summary>
        public static string TagMovimentoInvalid {
            get {
                return ResourceManager.GetString("TagMovimentoInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome não pode ser duplicado.
        /// </summary>
        public static string TagNomeDuplicado {
            get {
                return ResourceManager.GetString("TagNomeDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome não foi enconterado.
        /// </summary>
        public static string TagNomeInvalid {
            get {
                return ResourceManager.GetString("TagNomeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome não pode ser nulo.
        /// </summary>
        public static string TagNomeNull {
            get {
                return ResourceManager.GetString("TagNomeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome deve conter de 6 a 250 caracteres.
        /// </summary>
        public static string TagNomeTamanho {
            get {
                return ResourceManager.GetString("TagNomeTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O periodo não pode ser duplicado.
        /// </summary>
        public static string TagPeriodoDuplicado {
            get {
                return ResourceManager.GetString("TagPeriodoDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O SAP não pode ser duplicado.
        /// </summary>
        public static string TagSapDuplicado {
            get {
                return ResourceManager.GetString("TagSapDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O SAP não foi encontrado.
        /// </summary>
        public static string TagSapInvalid {
            get {
                return ResourceManager.GetString("TagSapInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O SAP não pode ser null.
        /// </summary>
        public static string TagSapNull {
            get {
                return ResourceManager.GetString("TagSapNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Sap deve conter até 250 digitos.
        /// </summary>
        public static string TagSapTamanho {
            get {
                return ResourceManager.GetString("TagSapTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As senhas não considem.
        /// </summary>
        public static string TagSenhaDiferentes {
            get {
                return ResourceManager.GetString("TagSenhaDiferentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha não é valida.
        /// </summary>
        public static string TagSenhaInvalida {
            get {
                return ResourceManager.GetString("TagSenhaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha ou confirmação não pode ser nulo.
        /// </summary>
        public static string TagSenhaNull {
            get {
                return ResourceManager.GetString("TagSenhaNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter de 4 à 20 caracteres.
        /// </summary>
        public static string TagSenhaTamanho {
            get {
                return ResourceManager.GetString("TagSenhaTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuario não foi encontrado.
        /// </summary>
        public static string TagUsuarioNotFound {
            get {
                return ResourceManager.GetString("TagUsuarioNotFound", resourceCulture);
            }
        }
    }
}
